### ISSUE TITLE
Plots not coming up after running CWD model

### ISSUE THREAD

**Issue by jhreed1** [SpeedGoat/DiseaseMonitoring#1]
Hi there - after uploading data from SOP4CWD into the batch estimation tool and successfully running the model, there is no plots or interpretation tab in the Output section (as described in the manual).

Is there a fix or am I missing something?

**Comment by Huh** [comment]
@jhreed1 that is correct. It is possible for someone to run hundreds of models and showing all of that information is really cumbersome. The documentation should be updated to make this more clear as the documentation seems to only reference the single run behavior of the site and not the batch mode. I will put that on my todo list. 

If you use the reports tab the generated reports will contain plots, tables, and the interpretation. You get one report per group/batch. For example, the template that you can download to format your data has example data and if you were to run thost models and generate reports you will get one report for each unique entry in the Batch column, Ravalli and Missoula County.

If you have any issues with this please let me know and I will do my best to help.

Thanks for the feedback, 

Josh

**Comment by jhreed1** [comment]
Very helpful! I figured it out and will reach back if there is anything else - thank you!

**Comment by Huh** [comment]
Oh good, I am going to close this now, but please feel free to reopen if needed. Feedback is always appreciated.

Also, I edited your post to remove your contact information from the post.

Thanks,

Josh

**Comment by Huh** [comment]
Updated documentation in commit [f48dcaa](https://github.com/SpeedGoat/Help_Pages/commit/f48dcaa22f763dcc3fa22fdca518e5feed824f03)
